on:
  push:
jobs:
  recompile_all_compiles:
    name: Recompile all Compiles
    runs-on: ubuntu-24.02
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: compile
        run: |
          sudo apt-get install -y godot 
          godot --download-template linuxd
          godot --download-template windows
          godot --download-template android
          godot --download-template macos
          mkdir -p linuxbsd/debug
          mkdir -p linuxbsd/release
          mkdir -p windows/debug
          mkdir -p windows/release
          mkdir -p android/debug
          mkdir -p android/release
          mkdir -p macos/debug
          mkdir -p macos/release
          godot --path ${CWD}/Attack-Defend_RTS/attack-defend-rts --headless --export-release linuxbsd linuxbsd/release
          godot --path ${CWD}/Attack-Defend_RTS/attack-defend-rts --headless --export-release windows windows/release
          godot --path ${CWD}/Attack-Defend_RTS/attack-defend-rts --headless --export-release android android/release
          godot --path ${CWD}/Attack-Defend_RTS/attack-defend-rts --headless --export-release macos macos/release
          godot --path ${CWD}/Attack-Defend_RTS/attack-defend-rts --headless --export-debug linuxbsd linuxbsd/debug
          godot --path ${CWD}/Attack-Defend_RTS/attack-defend-rts --headless --export-debug windows windows/debug
          godot --path ${CWD}/Attack-Defend_RTS/attack-defend-rts --headless --export-debug android android/debug
          godot --path ${CWD}/Attack-Defend_RTS/attack-defend-rts --headless --export-debug macos macos/debug
