name: Create Release

on:
  push:

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        platform: [linux, windows, mac, android]
    steps:
      - name: Check out
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: calver
          increment: patch

      - name: Build
        id: build
        uses: felix-schindler/build-godot-action@v2.0.0
        with:
          name: attack-defend-rts
          projectDir: attack-defend-rts
          preset: ${{ matrix.platform }}
          debugMode: "true"

      - name: Create prerelease
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.version.outputs.version }}
          allowUpdates: true
          artifacts: ${{ steps.build.outputs.build }}
