name: Create Release

on:
  push:

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        platform: [Linux, Windows Desktop, macOS, Android]
    steps:
      - name: Check out
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Create Output Directory
        run: mkdir attack-defend-rts-compiles

      - name: Set up git
        run: |
          git config user.email "${GITHUB_ACTOR}"@users.noreply.github.com
          git config user.name "${GITHUB_ACTOR}"

      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: calver
          increment: patch

      - name: Build
        id: build
        uses: felix-schindler/build-godot-action@v2.0.0
        with:
          name: attack-defend-rts
          projectDir: attack-defend-rts
          preset: ${{ matrix.platform }}
          debugMode: "true"

      - name: Create prerelease
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.version.outputs.version }}
          allowUpdates: true
          artifacts: ${{ steps.build.outputs.build }}*

      - name: Git checkin
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          git commit -am "v${VERSION}"
          git tag "v${VERSION}"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          force: true
